mailto_list = ['zhongfu.zheng@itel-mobile.com',
               'jianhua.li@itel-mobile.com',
               'lei.dai@itel-mobile.com',
               'chongyi.pu@itel-mobile.com',
               'hanyue.yang@itel-mobile.com',
               'wei.zhang@itel-mobile.com',
               'jinlei.zhang@itel-mobile.com',
               'hu.qiao@itel-mobile.com',
               'shaolin.tian@itel-mobile.com',
               'chen.liu@itel-mobile.com',
               'junjie.shi@itel-mobile.com',
               'ming.gao@itel-mobile.com',
               'linnan.yao@itel-mobile.com',
               'meng.zhang@itel-mobile.com',
               'weixi.dou@itel-mobile.com',
               'chong.qu@itel-mobile.com',
               'hualong.zhang@itel-mobile.com',
               'meiyi.chen@itel-mobile.com',
               'qun.zhang@itel-mobile.com',
               'jianyu.liu@itel-mobile.com',
               'suwen.feng@itel-mobile.com',
               'shuiyuan.zhang@itel-mobile.com']
tester_list = ['zhongfu.zheng@itel-mobile.com',
               'jianhua.li@itel-mobile.com',
               'lei.dai@itel-mobile.com']
